### ISSUE TITLE
Another command doesn't work while doing ask or listen in the same chat

### ISSUE THREAD

**Issue by X-Gorn** [usernein/pyromod#10]
Can you allow another command to run while ask or listen is running at the same chat?

**Comment by usernein** [comment]
Nice idea! I guess it's possible
It's not possible right now because i created pyromod focusing on private conversations, more specifically the interaction of an user with a bot
I'll work on it, thx

**Comment by usernein** [comment]
Hello! Check the [new release](https://github.com/usernein/pyromod/releases/tag/v2.0.0)!

It implements identifiers which lets you specify when you want to listen from a specif user in the chat (this was already possible using filters). It also fixes the behavior of blocking the handling of other commands when there was an active and unmatched listener on the chat.

**Comment by szsupunma** [comment]
@usernein Ok Good :D

**Comment by X-Gorn** [comment]
@usernein wow! that was fast!! thanks for the update OwO.
