### ISSUE TITLE
Suggestion: if i write username instead of chat_id it could convert it to chat_id

### ISSUE THREAD

**Issue by Eikosa** [usernein/pyromod#15]
if i write username instead of chat_id it should convert it to chat_id

client.get_chat(chat_id) will work i think

**Comment by usernein** [comment]
I appreciate the suggestion!

Instead of calling `get_chat`, i think it's better to save the specified usernames on the listener and simply compare chat.username when listener is processing messages. This way we avoid extra calls to the API

It's planned for pyrogram v3.1!

**Comment by usernein** [comment]
Implemented in pyromod [v3.1.0](https://github.com/usernein/pyromod/releases/tag/v3.1.0)!!
