### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by Athirst1998** [usernein/pyromod#21]
```
from pyromod import listen
from pyromod.listen.listen import ListenerTimeout

@app.on_message()
async def test(_, message):
    print(message)
    
 
app.run()
```

when I send a message to channel , the bot raise this error:

'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File ".....venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "......venv/lib/python3.10/site-packages/pyromod/listen/listen.py", line 196, in check
    (message.chat.id, message.from_user.id, message.id),
AttributeError: 'NoneType' object has no attribute 'id'

how can I fix error?

**Comment by TAMILVIP007** [comment]
@Athirst1998 The code and error are no where related tho

**Comment by AbirHasan2005** [comment]
I got same error:
```
pyrogram.dispatcher - ERROR - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
  File "/usr/local/lib/python3.8/dist-packages/pyromod/listen/listen.py", line 196, in check
    (message.chat.id, message.from_user.id, message.id),
AttributeError: 'NoneType' object has no attribute 'id'
```
it's latest version from pypi

**Comment by Surendra9123** [comment]
@AbirHasan2005 try message.sender_chat.id

**Comment by Surendra9123** [comment]
@AbirHasan2005 https://t.me/pyrogramchat/535246 look here..

**Comment by IronGiu** [comment]
Same error, in same file listen.py happen if a group/supergroup or channel start a live broadcast (video call, group call or whatever you want to call it)! 
Without pyromod no error raised during group call.
To reproduce it, just include pyromod and start a group call in a group where your bot is (normal bot, not userbot)

**Comment by canwushuang** [comment]
from tg “My problem is solved
I added this code to the part where the pyromod gets an error
         if message.from_user is None:
             _id = message.sender_chat.id
         else:
             _id = message.from_user.id
And finally, instead of the previous parameter, I put _id”

**Comment by catty-dev** [comment]
i got the same error in my code only when I impost pyromod. with parogram alone it runs fine

**Comment by EDM115** [comment]
using v2.0.0, and constantly get the same error : 
```
2023-08-29 12:15:22,881 - ERROR - pyrogram.dispatcher - MainThread - 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/pyromod/listen/listen.py", line 196, in check
    (message.chat.id, message.from_user.id, message.id),
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by IronGiu** [comment]
> using v2.0.0, and constantly get the same error : 
> 
> ```
> 
> 2023-08-29 12:15:22,881 - ERROR - pyrogram.dispatcher - MainThread - 'NoneType' object has no attribute 'id'
> 
> Traceback (most recent call last):
> 
>   File "/venv/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
> 
>     if await handler.check(self.client, parsed_update):
> 
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/venv/lib/python3.11/site-packages/pyromod/listen/listen.py", line 196, in check
> 
>     (message.chat.id, message.from_user.id, message.id),
> 
>                       ^^^^^^^^^^^^^^^^^^^^
> 
> AttributeError: 'NoneType' object has no attribute 'id'
> 
> ```

I modified pyromod and fixed this error long time ago, this error happen because not all updates have chat.id or from_user.id or a message id, but pyromod use these on every request, for example if an update came from a channel or from live broadcast update of a group/channel etc message.from_user.id is not present at all! Not even as "None".

If you implement the code of the pull request #22 problem disappear and all work great even after many tests.

I hope that will be implemented asap!

**Comment by SpidyBoYz** [comment]
I am also getting the same error:

```
'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.heroku/python/lib/python3.11/site-packages/pyromod/listen/listen.py", line 196, in check
    (message.chat.id, message.from_user.id, message.id),
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
```

Using the latest version (i.e. **2.0.0**) from pypi

**Comment by usernein** [comment]
#30 fixes this!
Thank you for reporting and contributing!
