### ISSUE TITLE
Use one structure and naming on all methods

### ISSUE THREAD

**Issue by 411A** [usernein/pyromod#23]
The method `wait_for_click` only accepts `from_user_id` & then it throws `NoneType` error at some point, I think it's better to use one structure for all of them (using kwargs or `identifiers`, not `identifier`). It'd be less confusing that way.

**Comment by 411A** [comment]
+ Another problem, when using `wait_for_click`, the first tap on the button does nothing!!! it stuck on the button's loading effect (despite using `cb.answer()`) and you should tap twice to activate the button.

**Comment by usernein** [comment]
@411A 

> Another problem, when using wait_for_click, the first tap on the button does nothing!!! it stuck on the button's loading effect (despite using cb.answer()) and you should tap twice to activate the button.

If you're still facing this issue on pyromod `v3`, may you create another issue for it? Thanks!
