### ISSUE TITLE
Pyromod raising AttributeError: 'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by Fima2003** [usernein/pyromod#29]
I get this error, and from a little investigation it comes from waiting from messages from channels.

Traceback (most recent call last):
  File "/env/lib/python3.11/site-packages/pyrogram/dispatcher.py", line 226, in handler_worker
    if await handler.check(self.client, parsed_update):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/env/lib/python3.11/site-packages/pyromod/listen/listen.py", line 196, in check
    (message.chat.id, message.from_user.id, message.id),
                      ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

What does it mean, and can you fix it?

**Comment by WhaleFell** [comment]
The pyromod needs to be modified
Because pyromod listen does not determine if message.from_user.id exists or not.

**Comment by usernein** [comment]
Thanks for reporting!

Fixed in [pyromod v3](https://github.com/usernein/pyromod/releases/tag/v3.0.0)!
