### ISSUE TITLE
How to kill client.listen?

### ISSUE THREAD

**Issue by yeralexey** [usernein/pyromod#9]
Hi!) 

Using this patch and pretty happy with it, my thanks to author.

So the question might look a bit wierd, but.

I need to get, how can I stop client.listen process. So I tried to save in not like "answer" as it shown in example, but as attribute of user object of my User class, that collects registering data of users.

Each object of user class is defined with id, so it looks like 

`user.answer = client.listen(chat_id, timeout=30)`

So it causes timeout error in 30 seconds, and I catch it with try except. So far it's pretty fine.

I hoped that if I start some other process I would simply do

`user.answer=None', an process of listening will stop. So... It doesn't)) I guess there is another link somewhere, that keeps this object alive and listening until timeout kills it. 

So, with hope I ask. How to kill it manually?)

**Comment by usernein** [comment]
Hello! Sorry for the late response. If i got you right, you can use `client.cancel_listener(chat_id)` or even `user.cancel_listener()`.
I also think user.answer = None is cool, i'll study the availability of doing that

**Comment by yeralexey** [comment]
Thanks! client.cansel_listener works fine!

I cant get the behaivior, when Timeout error arrives and when it does not. Can timeout be used simehow to send message to chat, that awaitanse of answer is canselled by timeout?

**Comment by usernein** [comment]
Yeah, you can catch the timeout error to send the alert:

Something like this:

```python
try:
    # start listening here
except TimeoutError:
     await message.reply("Eh. I waited for too long.")
```

**Comment by usernein** [comment]
BTW i'm planning to rename "cancel_listener" and improve its usability on the next updates, but i don't know exactly which name to choose

And also i wanna say here that i created a chat on telegram for pyromod: [@pyromodchat](https://t.me/pyromodchat)

**Comment by yeralexey** [comment]
i will definately join.
